### ISSUE TITLE
Google Nest API Console Available

### ISSUE THREAD

**Issue by masonticehurst** [michael5r/mmm-nest-status#11]
I just received an email that Google has moved the Works with Nest program over to their new ["Nest Device Access" program](https://developers.google.com/nest/device-access).
API Documentation available here: https://developers.google.com/nest/device-access/traits

Any possibility this can be integrated to get this working again for those of us who can't register through Works with Nest anymore?

**Comment by fordsteve** [comment]
Cannot believe its finally arrived.

**Comment by tanvir586** [comment]
I received the email too.

**Comment by outlan** [comment]
Yes! It's finally out there. Would LOVE to see this code work again.

**Comment by mrandroidpeanuts** [comment]
yes please!

**Comment by humdinger44** [comment]
im hoping to see an mmm-nest-status update as well :)

**Comment by yoh33zy** [comment]
same here!!

**Comment by nepster-forever** [comment]
yes i too wait. i pay 5$ to get api on google but i dont now how use))))

**Comment by psycho2288** [comment]
same here. Tried looking for documentation on how to implement it but couldn't find anything yet.

Look like you need the Oauth code from the MM module to enter into the Google device access console first.

**Comment by RoninActual** [comment]
+1 from the 2021 crowd.  Let us know how we can help!

**Comment by michael5r** [comment]
Working on it now - should be available shortly. No support for Nest Protects in the new API, unfortunately :(

**Comment by michael5r** [comment]
Just released version 2.0 which switches over to Google Device Access - have had it running on my own mirror for a couple of days and it seems to be working fine:

https://github.com/michael5r/mmm-nest-status/releases/tag/2.0.0

I'm going to close this issue now - if you have any problems with the new version, please open up a new issue.
