### ISSUE TITLE
Request dependency no longer include in MagicMirror

### ISSUE THREAD

**Issue by relm923** [michael5r/mmm-nest-status#14]
### Issue
`mmm-nest-status` relies on the now deprecated [request](https://www.npmjs.com/package/request) module. This module was previously available to `mmm-nest-status` because `MagicMirror` included it. The dependency was remove in https://github.com/MichMich/MagicMirror/releases/tag/v2.15.0. `mmm-nest-status` fails to launch on MM >= `2.15.0`

### Fix
- Added explicit dependency on `mmm-nest-status` via `package.json`
- Remove `request` dependency entirely and switch to [node-fetch](https://www.npmjs.com/package/node-fetch) or similar module

**Comment by michael5r** [comment]
Thanks for the report - I'll get this fixed shortly.

**Comment by TotesNaross** [comment]
Apologies for a lack of understanding.  You seemed to have laid out the fix for the issue, but could you explain in further detail what I need to do to implement the fix?  Very new to this and trying to learn as I go.  Thanks!

**Comment by SimpleSon** [comment]
> Apologies for a lack of understanding. You seemed to have laid out the fix for the issue, but could you explain in further detail what I need to do to implement the fix? Very new to this and trying to learn as I go. Thanks!

I am in the same boat my friend.  Waiting on a reply.

**Comment by relm923** [comment]
Added PR (#18) to fix the issue

**Comment by JWilson5607** [comment]
Fairly new to Git, but once the pull request is approved by michael5r, it will merge in to the code here and we can update/install it and it will work then, correct?

**Comment by slykeopath** [comment]
> Fairly new to Git, but once the pull request is approved by michael5r, it will merge in to the code here and we can update/install it and it will work then, correct?

Good question, I am waiting for this fix as well. Thank you all who support this, it is much appreciated!

**Comment by JWilson5607** [comment]
> > Fairly new to Git, but once the pull request is approved by michael5r, it will merge in to the code here and we can update/install it and it will work then, correct?
> 
> Good question, I am waiting for this fix as well. Thank you all who support this, it is much appreciated!

I was able to bypass the issue with running the following command in the modules\mmm-nest-status\ folder:
`npm install request`

I am not getting an API error which means I need to check something else

**Comment by michael5r** [comment]
Sorry about the delay, guys -  regular work has been crazy busy.

I just published a new version of this module that replaces `request` with `axios`, so it should work just fine in newer MM installs.

https://github.com/michael5r/mmm-nest-status/pull/21
