### ISSUE TITLE
Rate limit issues..

### ISSUE THREAD

**Issue by anthony6608** [michael5r/mmm-nest-status#7]
Hi,

Thanks for this wonderful module and the detailed instructions. I know in the readme you stated nothing can be done regarding the rate limit block however as soon as I enabled the module I was blocked within the first 10 minutes. I dont care too much for instantaneous updates, is there a way to adjust this? Ive been blocked and it doesnt seem to be pulling any data from my nest since. Thanks in advance!

**Comment by michael5r** [comment]
That sounds a bit odd - you shouldn't have been blocked that fast unless you were constantly refreshing the Nest feed; I've only been blocked once and that was when I was actually building this module (and kept refreshing to test things).

Anyway .. try setting the `updateInterval` to a higher number - it's in milliseconds, so I'd suggest trying something like `240000` (which is 4 minutes).

As a sidenote, I use 3 minutes myself and never have any issues.

**Comment by anthony6608** [comment]
Michael,

Thanks for the quick reply. I actually realized that I had two instances of MM running for some reason so I’m wondering if that caused it? 

Also do you know of anyway I can actually adjust the thermostat from magic mirror to make it more interactive? Thanks again for this awesome module!

**Comment by anthony6608** [comment]
Check

**Comment by michael5r** [comment]
It really depends on two things - which version of this module you're using and whether you're using the same Nest token for both instances. 

If you're using the latest version (or, at least, version `1.2.0` or above), multiple instances of this module that use the **same** Nest token will share Nest data - so you're only doing one data call to feed multiple sources. That wasn't the case when I initially launched this module.

If you're using different Nest tokens for different instances of this module, they will not share data - so I wouldn't recommend doing that.

In regards to adjusting the thermostat through the mirror, it's something I'm planning on adding in the future, but currently the module doesn't support this - sorry.

**Comment by anthony6608** [comment]
Hi Michael,

I assumed it was two instances because when I typed pm2 list it showed magicmirror and mm. Also I noticed when I minimzed MM to desktop I had two seperate browsers running magic mirror and my Pi was crashing a lot. Mich replied back to one of my questions regarding the two instances and he said one is the actual magicmirror and the other is the start up script used by pm2? But since i removed mm my pi hasn't crashed, nest hasnt blocked me (its been running all night) and when I reboot magic mirror and everything else runs fine. Any ideas whats going on?

**Comment by michael5r** [comment]
Michael is right - something went wrong when you set up `pm2` which means that you ended up with multiple instances of the magic mirror which, in turn, led to you doing doing 2 calls for Nest data every time the mirror refreshed. That would definitely explain the block.

**Comment by anthony6608** [comment]
It seems I'm having the issue again. When I load mm in my laptops browser is that an entirely separate call or is it pulling the already obtained data from the MagicMirror? I got rate limited since last night (over 14 hours ago) and turned off my magic mirror .. 14 hours later I am still getting the rate limiting errors. I have my MM set to 120000ms.

**Comment by michael5r** [comment]
Every instance of the magic mirror module is separate, so if you have it running on a mirror and also on your laptop, it's two instances & two data calls to the Nest API - that's probably why you're being limited. If this happens again, try bumping the `updateInterval` to 3 or 4 minutes.
