### ISSUE TITLE
Nest developer account

### ISSUE THREAD

**Issue by macoopma** [michael5r/mmm-nest-status#8]
Hello,

Looks like the Nest API is shutting down and has to be replaced by a google home API, it also looks like I can't make a NEST developer account anymore. Any plans to update this great module ?
Thanks,
Mathias.

**Comment by michael5r** [comment]
As soon as Google has their Device Access program up & running, I'll do my best to get the module updated.

For now, check out my note here:
https://github.com/michael5r/mmm-nest-status/pull/10
